# Generated by Django 4.2.7 on 2024-02-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(primary_key=True, serialize=False)),
                ('adress_line_1', models.CharField(max_length=30)),
                ('address_line2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('College_id', models.UUIDField(primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField()),
                ('seamster', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('college_name', models.CharField(max_length=30)),
                ('university_name', models.CharField(max_length=30)),
                ('date_of_enrollment', models.CharField(max_length=30)),
                ('college_roll_no', models.PositiveIntegerField(error_messages={'message': 'College roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField()),
                ('year_of_passing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contact_number', models.PositiveIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('contact_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=30)),
                ('points_or_marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TenSchoolingDetails',
            fields=[
                ('tenth_roll_no', models.PositiveIntegerField(error_messages={'message': 'Matriculation roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('board_name', models.CharField(max_length=30)),
                ('date_of_enrollment', models.CharField(max_length=30)),
                ('insert_date', models.DateTimeField()),
                ('year_of_passing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TwelfthSchoolingDetails',
            fields=[
                ('school_name', models.CharField(max_length=30)),
                ('board_name', models.CharField(max_length=30)),
                ('date_of_enrollment', models.CharField(max_length=30)),
                ('twelfth_roll_no', models.PositiveIntegerField(error_messages={'message': 'Inter roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField()),
                ('year_of_passing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Twelfth',
            fields=[
                ('Twelfth_id', models.UUIDField(primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Tenth',
            fields=[
                ('ten_id', models.UUIDField(primary_key=True, serialize=False)),
                ('insert_date', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('parent_id', models.UUIDField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=30)),
                ('other_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.otherdetails')),
                ('parent_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.name')),
            ],
        ),
        migrations.CreateModel(
            name='FullApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.address')),
                ('basic_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.college')),
                ('college_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.collegedetails')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.name')),
                ('parent_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.parentdetails')),
                ('tenth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.tenth')),
                ('tenth_schooling_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.tenschoolingdetails')),
                ('twelfth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.twelfth')),
                ('twelfth_schooling_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.twelfthschoolingdetails')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.subject'),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.name'),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='other_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.otherdetails'),
        ),
    ]
