# Generated by Django 4.2.7 on 2024-03-27 13:52

import Application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetail',
            fields=[
                ('reference_number', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('titles', models.CharField(choices=[('M01', 'Mrs'), ('M02', 'Miss'), ('M03', 'Mr'), ('D01', 'Dr')], max_length=30, null=True)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('middleName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Basic',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('semesterYear', models.CharField(choices=[('YO1', 'FIRST'), ('YO2', 'SECOND'), ('YO3', 'THIRD'), ('YO4', 'FOURTH'), ('YO5', 'FIFTH'), ('YO6', 'SIXTH'), ('YO7', 'SEVEN')], max_length=30, null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('semesterNumber', models.CharField(choices=[('SEM1', 'SEMESTER 1'), ('SEM2', 'SEMESTER 2'), ('SEM3', 'SEMESTER 3'), ('SEM4', 'SEMESTER 4'), ('SEM5', 'SEMESTER 5'), ('SEM6', 'SEMESTER 6'), ('SEM7', 'SEMESTER 7'), ('SEM8', 'SEMESTER 8')], max_length=100, null=True)),
                ('college_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='Application.college')),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Twelfth',
            fields=[
                ('twelfth_id', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='TwelfthSchoolingDetail',
            fields=[
                ('twelfthRollNo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30, null=True)),
                ('boardName', models.CharField(max_length=30, null=True)),
                ('dateOfEnrollment', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('yearOfPassing', models.CharField(max_length=30, null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
                ('twelfth_refrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twelfth', to='Application.twelfth')),
            ],
            options={
                'db_table': 'TwelfthSchoolingDetail',
            },
        ),
        migrations.CreateModel(
            name='Tenth',
            fields=[
                ('tenth_id', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'Tenth',
            },
        ),
        migrations.CreateModel(
            name='TenSchoolingDetail',
            fields=[
                ('tenthRollNo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30, null=True)),
                ('boardName', models.CharField(max_length=30, null=True)),
                ('dateOfEnrollment', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('yearOfPassing', models.CharField(max_length=30, null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
                ('tenth_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenth', to='Application.tenth')),
            ],
            options={
                'db_table': 'TenSchoolingDetail',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summaryId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('matricPercentage', models.FloatField(null=True)),
                ('interPercentage', models.FloatField(null=True)),
                ('graduationPercentage', models.FloatField(null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'Summary',
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('semesterSubjectId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('subjectCode', models.CharField(max_length=100, null=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('isUpdated', models.BooleanField(default=False, null=True)),
                ('semester_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterSubject', to='Application.semester')),
            ],
            options={
                'db_table': 'SemesterSubject',
            },
        ),
        migrations.CreateModel(
            name='ResponseObjectStudent',
            fields=[
                ('responseId', models.CharField(default=Application.models.create_new_ref_number, primary_key=True, serialize=False)),
                ('reference_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'ResponseObject',
            },
        ),
        migrations.CreateModel(
            name='ParentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titles', models.CharField(choices=[('M01', 'Mrs'), ('M02', 'Miss'), ('M03', 'Mr'), ('D01', 'Dr')], max_length=30, null=True)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('middleName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('relationship', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('navigationId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('path', models.JSONField(null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('matriculation_Id', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('subjectCode', models.CharField(max_length=100, null=True)),
                ('tenth_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculation', to='Application.tenth')),
            ],
            options={
                'db_table': 'Matriculation',
            },
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('intermediateId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('subjectCode', models.CharField(max_length=100, null=True)),
                ('twelfth_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate', to='Application.twelfth')),
            ],
            options={
                'db_table': 'Intermediate',
            },
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('collegeRollNo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=30, null=True)),
                ('universityName', models.CharField(max_length=30, null=True)),
                ('dateOfEnrollment', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('yearOfPassing', models.CharField(max_length=30, null=True)),
                ('academicYear', models.ManyToManyField(to='Application.college')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'CollegeDetail',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adressLine1', models.CharField(max_length=30, null=True)),
                ('addressLine2', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pincode', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('telephoneCode', models.CharField(choices=[('+91', 'IND'), ('+1', 'US'), ('+27', 'SA'), ('+44', 'UK'), ('+61', 'AUS')], max_length=12, null=True)),
                ('contactNumber', models.PositiveIntegerField(null=True)),
                ('emailId', models.EmailField(max_length=254, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.address')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetail')),
            ],
            options={
                'db_table': 'Additional',
            },
        ),
    ]
