# Generated by Django 4.2.7 on 2024-03-09 07:43

import Application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('reference_number', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('titles', models.CharField(choices=[('M01', 'Mrs'), ('M02', 'Miss'), ('M03', 'Mr'), ('D01', 'Dr')], max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Basic',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('seamster', models.CharField(choices=[('SEM1', 'SEMSTER 1'), ('SEM2', 'SEMSTER 2'), ('SEM3', 'SEMSTER 3'), ('SEM4', 'SEMSTER 4'), ('SEM5', 'SEMSTER 5'), ('SEM6', 'SEMSTER 6'), ('SEM7', 'SEMSTER 7'), ('SEM8', 'SEMSTER 8')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='ResponseObjectStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ResponseObject',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=100)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semster', to='Application.college')),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StudentDetails',
            },
        ),
        migrations.CreateModel(
            name='TwelfthSchoolingDetails',
            fields=[
                ('twelfthRollNo', models.PositiveIntegerField(error_messages={'message': 'Inter roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30)),
                ('boardName', models.CharField(max_length=30)),
                ('dateOfEnrollment', models.CharField(max_length=30)),
                ('insertDate', models.DateTimeField()),
                ('yearOfPassing', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'TwelfthSchoolingDetails',
            },
        ),
        migrations.CreateModel(
            name='Twelfth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Twelfth',
            },
        ),
        migrations.CreateModel(
            name='Tenth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Tenth',
            },
        ),
        migrations.CreateModel(
            name='TenSchoolingDetails',
            fields=[
                ('tenthRollNo', models.PositiveIntegerField(error_messages={'message': 'Matriculation roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30)),
                ('boardName', models.CharField(max_length=30)),
                ('dateOfEnrollment', models.CharField(max_length=30)),
                ('insertDate', models.DateTimeField()),
                ('yearOfPassing', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'TenSchoolingDetails',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('matricPercentage', models.FloatField()),
                ('interPercentage', models.FloatField()),
                ('graduationPercentage', models.FloatField()),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Summary',
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subjectCode', models.CharField(max_length=100)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterSubject', to='Application.semester')),
            ],
            options={
                'db_table': 'SemsterSubject',
            },
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titles', models.CharField(choices=[('M01', 'Mrs'), ('M02', 'Miss'), ('M03', 'Mr'), ('D01', 'Dr')], max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('subjectId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subjectCode', models.CharField(max_length=100)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matriculation', to='Application.tenth')),
            ],
            options={
                'db_table': 'Matriculation',
            },
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('subjectId', models.CharField(blank=True, default=Application.models.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subjectCode', models.CharField(max_length=100)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Intermediate', to='Application.twelfth')),
            ],
            options={
                'db_table': 'Intermediate',
            },
        ),
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('collegeRollNo', models.PositiveIntegerField(error_messages={'message': 'College roll number cannot be empty'}, primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=30)),
                ('universityName', models.CharField(max_length=30)),
                ('dateOfEnrollment', models.CharField(max_length=30)),
                ('insertDate', models.DateTimeField()),
                ('yearOfPassing', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'CollegeDetails',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adressLine1', models.CharField(max_length=30)),
                ('addressLine2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('telephoneCode', models.CharField(choices=[('+91', 'IND'), ('+1', 'US'), ('+27', 'SA'), ('+44', 'UK'), ('+61', 'AUS')])),
                ('contactNumber', models.PositiveIntegerField()),
                ('emailId', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.address')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.basicdetails')),
            ],
            options={
                'db_table': 'Additional',
            },
        ),
    ]
